### ISSUE TITLE
Convice Kami to do shit

### ISSUE THREAD

**Issue by DircerollGerb** [DircerollGerb/MarketGarden#1]
## Description

We've decided to work together with the infamous DicerollKami. A lot of potential, but he didn't show this yet.
It's a had to motivate guy so we need to tackle some obstacles first.

### The plan

- Motivate Kami to use GitHub
- Give him a heads up everyday (Don't be scared to annoy him)
- Give him small tasks

### Tasks
- [x] <- @DicerollKami Finish the GitHub registration by verifying your e-mail
- [x] <- @DicerollKami check this box within a week

**Comment by DicerollKami** [comment]
Prachtig
